version: '2.23'

services:
  
  catalog.api:
    container_name: lde.catalog.api
    build:
      context: .
      dockerfile: ../Catalog/Catalog.Host/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionString=server=host.docker.internal;port=5432;database=catalog;uid=postgres;password=postgres;
    depends_on:
      - postgres
    ports:
      - 5000:5000
  
  nginx:
    image: nginx:latest
    container_name: lde.nginx
    ports:
      - 8080:8080
    volumes:
      - ./Proxy/gateway/nginx/default.conf:/etc/nginx/conf.d
  
  pgadmin4:
    image: dpage/pgadmin4
    container_name: lde.pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - postgres
    ports:
      - 8001:80
      
  identityserver:
    container_name: lde.identityserver
    build:
      context: .
      dockerfile: ../IdentityServer/IdentityServer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
      - CatalogApi=http://localhost:5000
    ports:
      - 5001:5001
      
  postgres:
    image: postgres
    container_name: lde.postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

networks:
  default:
    driver: bridge
    internal: false
    ipam:
      driver: default
      config:
        - subnet: 192.172.0.4/24
          gateway: 192.172.0.4