# This is a generated file. Not intended for manual editing.
version: "2.23"
services:
  catalog.api:
    build:
      context: "D:\\dev\\A_LEVEL\\eShop\\SolutionItems"
      dockerfile: "../Catalog/Catalog.Host/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Catalog.Host.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "catalog.host:dev"
    ports: []
    volumes:
    - "C:\\Users\\vovko\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\dev\\A_LEVEL\\eShop\\Catalog\\Catalog.Host:/app:rw"
    - "D:\\dev\\A_LEVEL\\eShop:/src:rw"
    working_dir: "/app"
  web.mvc:
    build:
      context: "D:\\dev\\A_LEVEL\\eShop\\SolutionItems"
      dockerfile: "../MVC/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/MVC.dll"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/MVC.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "mvc:dev"
    ports: []
    volumes:
    - "C:\\Users\\vovko\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\dev\\A_LEVEL\\eShop\\MVC:/app:rw"
    - "D:\\dev\\A_LEVEL\\eShop:/src:rw"
    working_dir: "/app"
